"""Stable domain enumeration values stored as strings."""

from enum import StrEnum


class RoleKey(StrEnum):
    ADMIN = "ADMIN"
    SUPPLY_CHAIN_MANAGER = "SUPPLY_CHAIN_MANAGER"
    SUPPLY_CHAIN_PLANNER = "SUPPLY_CHAIN_PLANNER"
    PROCUREMENT = "PROCUREMENT"
    APPROVER = "APPROVER"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class FacilityType(StrEnum):
    PLANT = "PLANT"
    WAREHOUSE = "WAREHOUSE"
    DISTRIBUTION_CENTER = "DISTRIBUTION_CENTER"


class RecordStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"


class ShipmentStatus(StrEnum):
    PLANNED = "PLANNED"
    IN_TRANSIT = "IN_TRANSIT"
    DELAYED = "DELAYED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class SignalCategory(StrEnum):
    WEATHER_DISRUPTION = "WEATHER_DISRUPTION"
    SUPPLIER_SHUTDOWN = "SUPPLIER_SHUTDOWN"
    SUPPLIER_DELAY = "SUPPLIER_DELAY"
    PORT_CLOSURE = "PORT_CLOSURE"
    TRANSPORT_DISRUPTION = "TRANSPORT_DISRUPTION"
    QUALITY_ISSUE = "QUALITY_ISSUE"
    GEOPOLITICAL_DISRUPTION = "GEOPOLITICAL_DISRUPTION"
    CAPACITY_PROBLEM = "CAPACITY_PROBLEM"
    INVENTORY_ANOMALY = "INVENTORY_ANOMALY"
    LATE_PURCHASE_ORDER = "LATE_PURCHASE_ORDER"
    MANUAL_DISRUPTION = "MANUAL_DISRUPTION"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"


class IncidentStatus(StrEnum):
    DETECTED = "DETECTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACTIVE = "ACTIVE"
    MITIGATION_PROPOSED = "MITIGATION_PROPOSED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    MITIGATING = "MITIGATING"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class RiskBand(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ScenarioStatus(StrEnum):
    DRAFT = "DRAFT"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    RECOMMENDED = "RECOMMENDED"
    SELECTED = "SELECTED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class VerificationStatus(StrEnum):
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    FAILED = "FAILED"
    REQUIRES_NEW_MITIGATION = "REQUIRES_NEW_MITIGATION"


class WorkflowVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class FailurePolicy(StrEnum):
    FAIL_WORKFLOW = "FAIL_WORKFLOW"
    SKIP_STAGE = "SKIP_STAGE"
    CONTINUE = "CONTINUE"


class ConnectorStatus(StrEnum):
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    ERROR = "ERROR"
    MOCK_MODE = "MOCK_MODE"


class NotificationStatus(StrEnum):
    UNREAD = "UNREAD"
    READ = "READ"
    DISMISSED = "DISMISSED"


class LLMRunStatus(StrEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
