"""Canonical persisted domain model exports.

Importing this package registers every table on ``Base.metadata`` for Alembic.
"""

from app.domain.models.disruption import (
    ApprovalDecision,
    ApprovalRequest,
    DisruptionIncident,
    ExecutionAction,
    ExecutionResult,
    ExternalSignal,
    ImpactAssessment,
    ImpactMetric,
    IncidentEntity,
    IncidentSignal,
    Recommendation,
    RiskAssessment,
    RiskFactor,
    Scenario,
    ScenarioAction,
    SignalSource,
    VerificationResult,
)
from app.domain.models.identity import Organization, Role, User, UserRole
from app.domain.models.operations import (
    Customer,
    CustomerOrder,
    CustomerOrderLine,
    PurchaseOrder,
    PurchaseOrderLine,
    Shipment,
    ShipmentEvent,
)
from app.domain.models.platform import (
    AuditLog,
    Connector,
    ConnectorRun,
    LLMModelConfiguration,
    LLMRun,
    Notification,
    PromptTemplate,
)
from app.domain.models.supply import (
    BillOfMaterial,
    BOMComponent,
    ConsumptionHistory,
    DistributionCenter,
    Facility,
    InventorySnapshot,
    Material,
    MaterialSupplier,
    Plant,
    Product,
    Supplier,
    SupplierRating,
    SupplierSite,
    Warehouse,
)
from app.domain.models.workflow import (
    StageConfiguration,
    StageDefinition,
    StageDependency,
    StageRun,
    WorkflowDefinition,
    WorkflowRun,
    WorkflowVersion,
)

__all__ = [
    "ApprovalDecision",
    "ApprovalRequest",
    "AuditLog",
    "BOMComponent",
    "BillOfMaterial",
    "Connector",
    "ConnectorRun",
    "ConsumptionHistory",
    "Customer",
    "CustomerOrder",
    "CustomerOrderLine",
    "DisruptionIncident",
    "DistributionCenter",
    "ExecutionAction",
    "ExecutionResult",
    "ExternalSignal",
    "Facility",
    "ImpactAssessment",
    "ImpactMetric",
    "IncidentEntity",
    "IncidentSignal",
    "InventorySnapshot",
    "LLMModelConfiguration",
    "LLMRun",
    "Material",
    "MaterialSupplier",
    "Notification",
    "Organization",
    "Plant",
    "Product",
    "PromptTemplate",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "Recommendation",
    "RiskAssessment",
    "RiskFactor",
    "Role",
    "Scenario",
    "ScenarioAction",
    "Shipment",
    "ShipmentEvent",
    "SignalSource",
    "StageConfiguration",
    "StageDefinition",
    "StageDependency",
    "StageRun",
    "Supplier",
    "SupplierRating",
    "SupplierSite",
    "User",
    "UserRole",
    "VerificationResult",
    "Warehouse",
    "WorkflowDefinition",
    "WorkflowRun",
    "WorkflowVersion",
]
